# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa55341d9777e96d768c4895b6438c7c654afcfff0afa837e0917953df73c97f1314fa96c8a486e5f6af21ea0c634e742e604a1b9f4924f60ed9974c6b1fc828

test:
  secret_key_base: 890dba5d66d1bc0117b6d8ea8b7e55bb6359524831003d5f56a20d65973fe56f45558852e03963d8c3f1c0d69647a4546cda32c6157728a349f8463c5c882303

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
